import Configuration from "../Configuration";
import React from "react";

const BASE_URL = Configuration.devUrl;
const UI_BASE_URL = Configuration.Api_devUrl;

const API_URL = {
  GET_POST: BASE_URL + "post/allpostsPaginated?page=1",
  GET_POST_PAGINATED: BASE_URL + "post/allpostsPaginated?page=",
  GET_POST_PAGINATED_PRIVATE: BASE_URL + "post/privatePostsPaginated?page=",
  GET_POST_NOT_PAGINATED_PRIVATE:
    BASE_URL + "Post/getPrivatePostsOfCurrentUser",

  Get_POST_TAGGED: BASE_URL + "Notification/findPost",
  GET_USERS_TO_ADD_COMMITTEE: BASE_URL + "Users/Display/AddUsersToNewCommittee",
  GET_ALL_POST: BASE_URL + "post/allposts",
  GET_TOTAL_SCORE: BASE_URL + "TotalPoint/Get/EventId/GroupIdAndSumGroup1",
  GET_TOTAL_SCORE_EVENT_WISE: BASE_URL + "TotalPoint/eventWiseGroupTotalPoint",

  POST_UPLOAD_CSV: BASE_URL + "Auth/upload",
  GET_LIST_ALL_USERS: BASE_URL + "users/display/All/user",
  GET_DESIGNATION: BASE_URL + "Designation/get",
  POST_DELETE_USERS: BASE_URL + "auth/delete/user/",
  POST_UPDATE_USER_TYPE: BASE_URL + "auth/update/user/type/",
  POST_ADD_USER: BASE_URL + "auth/add/user/manually",
  POST_CHANGE_USER_PASSWORD: BASE_URL + "Auth/jwt/ChangePassword",
  GET_ALL_EVENTS:
    BASE_URL + "event/allevent?page=1&LIMIT=10&sortOrder=1&sortBy=EventName",
  GET_ALL_EVENTS_QUARTERS: BASE_URL + "Event/getQuarterEvents",
  POST_GAME_LIST_EVENT_WINNER:
    BASE_URL + "TotalPoint/Get/EventId/GroupIdAndSumEvent1Winners/",
  GET_CURRENT_EVENT: BASE_URL + "Event/currentevents",
  GET_EVENT_WISE_GROUP: BASE_URL + "Group/GetEventBaseGroup/",
  POST_LIST_GAME: BASE_URL + "TotalPoint/Get/EventId/GroupId",
  POST_TOTAL_POINT_PUBLISH_COMMITTEE:
    BASE_URL + "TotalPoint/publishToCommittee/",
  POST_UPDATE_POINT: BASE_URL + "TotalPoint/Get/Update/",
  POST_LIST_GAME_EVENT_ID: BASE_URL + "game/EventId",
  POST_LIST_EVENT_WINNER:
    BASE_URL + "TotalPoint/Get/EventId/GroupIdAndSumEvent1Winner",
  GET_LIST_USERS_SET_ROLE:
    BASE_URL + "Group/FindUsersOfAGroupWithoutCommitteeMember/",
  GET_USERS_TO_ADD_GROUP: BASE_URL + "users/Display/AddUsersToNewGroup",
  PUT_ADD_GROUP_MEMBER: BASE_URL + "group/Update/Multiple/UsersGroup/",
  GET_LIST_GROUP_MEMBER: BASE_URL + "Group/FindAllUser/inGroup/",
  PUT_DELETE_GROUP_MEMBER: BASE_URL + "Group/Update/Single/UserGroup/",
  PUT_CHANGE_GROUP_ROLE: BASE_URL + "users/updateGroupCapandVC/",
  GET_EMAIL_SEARCH: BASE_URL + "users/findByEmailRegexForGroup/",
  POST_CREATE_GROUP: BASE_URL + "Group/create",
  GET_LIST_GROUP: BASE_URL + "Group/findAllGroup",
  PUT_DELETE_GROUP: BASE_URL + "Group/Delete/CommitteeOrGroup/",
  GET_SINGLE_GROUP: BASE_URL + "Group/findGroupById/",
  PUT_UPDATE_GROUP: BASE_URL + "Group/UpdateGroupDetails/",
  PUT_UPDATE_GROUP_IMAGE: BASE_URL + "Group/UpdatePic/",
  POST_TOTAL_POINT: BASE_URL + "TotalPoint/Get/EventId/GroupIdAndSumGroup2",
  GET_POINT_TO_PUBLISH:
    BASE_URL + "TotalPoint/Get/EventId/GroupIdAndSumGroup1forpublish",
  POST_PUBLISH_POINT: BASE_URL + "PublishToInno/Add",
  POST_POINTS_PUBLISHED_TO_COMMITTEE:
    BASE_URL + "TotalPoint/GetpublishToCommittee",
  POST_PUBLISH_EVENT_POINT: BASE_URL + "/TotalPoint/UpdatePublishToInnovature/",
  POST_FIND_COMMITTEE: BASE_URL + "Group/FindCommittee",
  GET_LIST_COMMITTEE_MEMBERS: BASE_URL + "Group/FindAllUser/inCommittee/",
  PUT_ADD_COMMITTEE_MEMBER: BASE_URL + "group/Update/Multiple/UsersCommittee/",
  GET_COMMITTEE_EMAIL_SEARCH: BASE_URL + "users/findByEmailInMaterial/",
  GET_LIST_COMMENT: BASE_URL + "comment/listcomment/",
  DELETE_ALL_POST: BASE_URL + "post/deletepostbyadmin/",
  REPORTED_POINTS: BASE_URL + "TotalPoint/reportedPoints",
  GET_SEARCH: BASE_URL + "Users/searchOnInnovators/",
  GET_QUATERLIST: BASE_URL + "Event/getCurrentYearsQuarters",
  ADD_QUATER: BASE_URL + "Event/createQuarter",
  EDIT_QUATER: BASE_URL + "Event/editQuater",
  GET_QUATER_HISTORY: BASE_URL + "TotalPoint/quarterWiseTotalpoints/",
  RESET_QUATER: BASE_URL + "TotalPoint/quaterResetManually",
  YEARLY_RESET: BASE_URL + "Event/yearlyReset",
  POST_IMAGE_ADMIN: BASE_URL + "Users/addImage",
  GET_IMAGE_ADMIN: BASE_URL + "Users/getImage",
  PUT_DELETE_IMAGE: BASE_URL + "Users/deleteImage",

  POST_EVENT_SWITCH_GROUP: BASE_URL + "event/eventswithgroupame",
  POST_GAME_POINT_GROUP_NAME: BASE_URL + "game/GamePointWithGroupName",
  GET_PUBLISHED_POINT: BASE_URL + "PublishToInno/GetPublish",
  GET_CURRENT_EVENT_SWITCH_GROUP: BASE_URL + "event/currenteventswithgroupame",
  GET_GROUP_GROUP_MEMBERS: BASE_URL + "group/groupnameandmembers",
  GET_POST_CURRENT_USER: BASE_URL + "post/postofcurrentUser",
  POST_LIKE_POST: BASE_URL + "like/dislikepost",
  POST_POST_LIKE: BASE_URL + "like/likepost",
  DELETE_POST: BASE_URL + "post/deletepost/",
  POST_ADD_COMMENT: BASE_URL + "comment/postcomment",
  POST_EDIT_COMMENT: BASE_URL + "comment/editcomment",
  POST_DELETE_COMMENT: BASE_URL + "comment/deletecomment",

  PUT_UPDATE_PROFILE_PIC: BASE_URL + "Users/UpdatePic/",
  POST_CHANGE_PASSWORD: BASE_URL + "Auth/jwt/ChangePswd/Home",
  GET_CURRENT_USER_DETAILS: BASE_URL + "Users/currentuserDetails",
  PUT_UPDATE_USER: BASE_URL + "Users/UpdateUser/",
  POST_POST_IMAGE: BASE_URL + "post/postimage",
  POST_EDIT: BASE_URL + "post/postimageEdit",
  POST_PRIVATE_TO_PUBLIC: BASE_URL + "post/makePostPublic/",
  GET_SINGLE_POST_PRIVATE: BASE_URL + "Post/postbyIdPrivate/",

  POST_IMAGE_PRIVATE: BASE_URL + "post/postImagePrivate",
  POST_IMAGE_PRIVATE_EDIT: BASE_URL + "post/postImagePrivateEdit",

  GET_SINGLE_POST: BASE_URL + "Post/postbyId/",
  POST_CREATE_POLL: BASE_URL + "Poll/createPoll",
  GET_POLL_LIST: BASE_URL + "Poll/listAllPolls",
  DELETE_POLL: BASE_URL + "Poll/deletePoll/",
  GET_RECENT_POLL: BASE_URL + "Poll/getActivePolls",
  GET_SINGLE_POLL: BASE_URL + "Poll/getPollById/",
  PUT_EDIT_POLL: BASE_URL + "Poll/updatePoll/",
  BIRTHDAY_CURRENT_MONTH: BASE_URL + "Users/birthdaysOfCurrentMonth/",
  BIRTHDAY_CURRENT_WEEK: BASE_URL + "notification/findBirthdayUsers/",
  GAME_WISE_WINNER: BASE_URL + "game/gameWinners",
  EVENT_FIELD_SEARCH: BASE_URL + "event/eventSearch",
  SEARCH_GAME: BASE_URL + "game/gameSearch",
  REPORT_POST: BASE_URL + "Report/report",
  GLIMPSES_GET: BASE_URL + "Notification/getGlimpses",

  GET_SINGLE_POST_WITH_COMMENTS: BASE_URL + "Post/OnePostWithComments/",
  GET_ALL_EVENT: BASE_URL + "event/allevent",
  POST_CREATE_EVENT: BASE_URL + "event/postevent",
  GET_SINGLE_EVENT: BASE_URL + "event/eventbyId/",
  PUT_EVENT_UPDATE_EVENT: BASE_URL + "event/updateevent/",
  DELETE_EVENT: BASE_URL + "event/eventDelete/",
  POST_CREATE_GAME: BASE_URL + "game/postgame",
  GET_SINGLE_GAME: BASE_URL + "game/onegame/",
  PUT_UPDATE_GAME: BASE_URL + "game/updategame/",
  GET_ALL_GAME: BASE_URL + "game/allgame",
  POST_REPORT_POINT_LIST: BASE_URL + "TotalPoint/notverifiedPoint/",
  POST_VERIFY_POINT: BASE_URL + "TotalPoint/verifiedPoint/",
  GET_GAME_IN_EVENT: BASE_URL + "game/game/",
  DELETE_GAME: BASE_URL + "game/deleteGame/",
  POST_POLL_VOTING: BASE_URL + "Poll/votePoll",
  GET_GAME_WINNERS: BASE_URL + "game/gameWinners",
  GET_USER_DETAILS: BASE_URL + "Users/getUserOrGroupDetails/",
  GET_POST_USER: BASE_URL + "Post/getPostsOfUser/",
  GET_TAGED_POST_USER: BASE_URL + "Notification/getTaggedPosts/",
  GET_COMMITTEE_POST: BASE_URL + "Post/getPostsOfCommittee",
  GET_UI_BASE_URL: UI_BASE_URL,
};

export default API_URL;
